apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicoapipod
  labels:
    app: medicoapipod
    environment: production
    team: dev
  annotations:
    description: "Deployment do aplicativo de medicos API"
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: medicoapipod
  template:
    metadata:
      labels:
        app: medicoapipod
        environment: production
        team: dev
      annotations:
        description: "Pod do aplicativo de medicos API"
    spec:
      containers:
      - name: medicoapipod
        image: fabaofloripa/msmedico.api:latest
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1

---

apiVersion: v1
kind: Service
metadata:
  name: medicoapipod-service
  labels:
    app: medicoapipod
    environment: production
    team: dev
  annotations:
    description: "Service para o aplicativo de medicos API"
spec:
  selector:
    app: medicoapipod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30101
  type: NodePort

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: medicoapipod-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: medicoapipod
  minReplicas: 1
  maxReplicas: 20  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
